name: 'Wechat Work Robot Messages'
description: 'Github Action for Sending Wechat Wrok robot messages'
author: 'xiexianbin <me@xiexianbin>'
inputs: 
  WECHAT_WEBHOOK_KEY:
    description: 'Wechat Work webhook key'
  MSGTYPE:
    description: 'message type (text, markdown, image, news)'
    default: "markdown"
  CONTENT:
    description: 'content of message (default "This is a text")'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: "blue"
  icon: "message-square"
