name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Sending Wechat Work Message
      uses: x-actions/wechat-work@master
      env:
        WECHAT_WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}
        MSGTYPE: test
        CONTENT: x-actions/wechat-work build success.
